# Site settings
title: Kamyab Abedi
description: My Home Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kamyab Abedi
user_description: Current I’m third year student of CE at Shahid Beheshti University and interested in Back‑end programming, IT security, ML and other geek stuff. 2+ years experience specializing in the backend development, infrastructure automation. Super nerd who loves Linux and enjoys to customize all of the development environment. Interested in devising a better problem‑solving method for challenging tasks, and learning new technologies and tools if the need arises. I’m passionate about my work. Because I love what I do, I have a steady source of motivation that drives me to do my best.
user_title: Software Engineer
email: kamyababedi@gmail.com
twitter_username: KamyabAbedi
github_username:  KamyabAbedi
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
